#!/bin/sh
# Usage: script/bootstrap
# Initializes your local environment for development

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

if [[ ! -x $(which appledoc) ]]; then
    echo "To build the Documentation target, you'll need to install appledoc: brew install appledoc"
fi

bundle install --binstubs --path Vendor/bundle
bundle exec pod install
