#!/bin/sh
# Usage: script/bootstrap
# Initializes your local environment for development

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

command -v appledoc >/dev/null 2>&1 ||
    echo "To build the Documentation target, you'll need to install appledoc: brew install appledoc"

bundle install --binstubs --path Vendor/bundle
bundle exec pod install
