.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 1/21/14
.Dt thingshub 1
.Os Darwin
.Sh NAME
.Nm thingshub
.\" Use .Nm macro to designate other names for the documented program.
.Nd Synchronize Github issues one-way into your task manager.
.Sh SYNOPSIS
.Nm
.Op Fl githubLogin Ar username
.Op Fl tagNamespace Ar namespace
.Op Fl delegate Ar delegate
.Op Fl map.labelName Ar tagName
.Op Fl repoOwner Ar username
.Op Fl repoName Ar repo
.Op Fl areaName Ar area
.Op Fl projectPrefix Ar prefix
.Op Fl version
.Sh DESCRIPTION
The simplest usage is just to run 
.Nm
and specify all configuration options on the command line.
.Pp
Alternatively, run 
.Nm
from a project's directory, optionally specifying configuration options via the CLI. 
.Nm
will configure itself from your configuration files as described below.
.Pp \" Inserts a space
.Bl -tag -width -indent
.It Fl githubLogin
Your Github username. Required.
.It Fl tagNamespace
Namespace to use as a prefix for tags imported from Github. Optional; default is 'github'.
.It Fl delegate
Sync delegate used to communicate with the local task maager app. Optional; default is 'Things'. Currently only Things is supported.
.It Fl map.labelName
Map a Github label to a local tag name. Optional. 
.Ar -"map.label name"
if you need spaces.
.It Fl repoOwner
The owner of the Github repo to sync. Required.
.It Fl repoName
The Github repo to sync. Required.
.It Fl areaName
The area in Things to use for this project. Optional; default is none.
.It Fl projectPrefix
Prefix which will be applied to project names. Optional; default is none.
.It Fl version
Print version information and exit.
.El                      \" Ends the list
.Pp
The flags above may all be specified in a .thingshubconfig file, without a leading dash, like
.Ar parameter = value.
.Sh CONFIGURATION FILES
.Nm
checks for a config file at ~/.thingshubconfig, then traverses from the home directory down to the current dir (or from the root to the current dir, if the current directory isn't in ~), merging in '.thingshubconfig' files as it finds them.
.Pp
This means you can put global configuration and defaults (eg. 'githubLogin', 'tagNamespace') in ~/.thingshubconfig, leaving project-specific settings (eg. 'repoOwner', 'repoName') in project/.thingshubconfig, sort of like using git's configuration system.
.Pp
Configuration parameters may additionally be specified on the command line:
.Ar -githubLogic cdzombak .
Parameters specified on the command line override those found in any configuration files.
.Pp
See thingshubconfig.example in this distribution for details on the configuration format.
.Pp
You may also want to add .thingshubconfig to your ~/.gitignore.
.Pp
.Ar https://github.com/cdzombak/thingshub/blob/master/thingshubconfig.example
.Sh LOGOUT
.Nm
does not have a UI to log out of Github. You may remove its Github OAuth credential from the Keychain via 'security delete-generic-password -s "ThingsHub-Github"'.
.Sh FILES                \" File used or created by the topic of the man page
.Bl -tag -width "/usr/local/share/man/man1/thingshub.1" -compact
.It Pa /usr/local/bin/thingshub
The
.Nm
binary
.It Pa /usr/local/share/man/man1/thingshub.1
This man page
.It Pa ~/.thingshubconfig
Default configuration file
.It Pa [../].thingshubconfig
Configuration files in the current and all parent directories
.El
.Sh VERSION
.Nm
version 1.0.1.
.Sh SEE ALSO
The project's README contains a workflow description, implementation details, dev instructions, and installation notes.
.Pp
.Ar https://github.com/cdzombak/thingshub/blob/master/README.md
.Sh BUGS              \" Document known, unremedied bugs 
.Ar https://github.com/cdzombak/thingshub/issues
.Sh CONTRIBUTORS
.Bl -tag -width "Andrew Sardone" -compact
.It Chris Dzombak
.Ar https://github.com/cdzombak
.It Andrew Sardone
.Ar https://github.com/andrewsardone
.El
